// Code generated by go-swagger; DO NOT EDIT.

package hardware_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider-zedcloud/v2/models"
)

// HardwareModelDeleteEdgeNodeReader is a Reader for the HardwareModelDeleteEdgeNode structure.
type HardwareModelDeleteEdgeNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HardwareModelDeleteEdgeNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHardwareModelDeleteEdgeNodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewHardwareModelDeleteEdgeNodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewHardwareModelDeleteEdgeNodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewHardwareModelDeleteEdgeNodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewHardwareModelDeleteEdgeNodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewHardwareModelDeleteEdgeNodeGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewHardwareModelDeleteEdgeNodeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHardwareModelDeleteEdgeNodeOK creates a HardwareModelDeleteEdgeNodeOK with default headers values
func NewHardwareModelDeleteEdgeNodeOK() *HardwareModelDeleteEdgeNodeOK {
	return &HardwareModelDeleteEdgeNodeOK{}
}

/*
HardwareModelDeleteEdgeNodeOK describes a response with status code 200, with default header values.

A successful response.
*/
type HardwareModelDeleteEdgeNodeOK struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node o k response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hardware model delete edge node o k response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node o k response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this hardware model delete edge node o k response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this hardware model delete edge node o k response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the hardware model delete edge node o k response
func (o *HardwareModelDeleteEdgeNodeOK) Code() int {
	return 200
}

func (o *HardwareModelDeleteEdgeNodeOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeOK  %+v", 200, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeOK) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeOK  %+v", 200, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeOK) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeUnauthorized creates a HardwareModelDeleteEdgeNodeUnauthorized with default headers values
func NewHardwareModelDeleteEdgeNodeUnauthorized() *HardwareModelDeleteEdgeNodeUnauthorized {
	return &HardwareModelDeleteEdgeNodeUnauthorized{}
}

/*
HardwareModelDeleteEdgeNodeUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type HardwareModelDeleteEdgeNodeUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node unauthorized response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this hardware model delete edge node unauthorized response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node unauthorized response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this hardware model delete edge node unauthorized response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this hardware model delete edge node unauthorized response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the hardware model delete edge node unauthorized response
func (o *HardwareModelDeleteEdgeNodeUnauthorized) Code() int {
	return 401
}

func (o *HardwareModelDeleteEdgeNodeUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeUnauthorized  %+v", 401, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeUnauthorized  %+v", 401, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeForbidden creates a HardwareModelDeleteEdgeNodeForbidden with default headers values
func NewHardwareModelDeleteEdgeNodeForbidden() *HardwareModelDeleteEdgeNodeForbidden {
	return &HardwareModelDeleteEdgeNodeForbidden{}
}

/*
HardwareModelDeleteEdgeNodeForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type HardwareModelDeleteEdgeNodeForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node forbidden response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this hardware model delete edge node forbidden response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node forbidden response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this hardware model delete edge node forbidden response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this hardware model delete edge node forbidden response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the hardware model delete edge node forbidden response
func (o *HardwareModelDeleteEdgeNodeForbidden) Code() int {
	return 403
}

func (o *HardwareModelDeleteEdgeNodeForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeForbidden  %+v", 403, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeForbidden) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeForbidden  %+v", 403, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeNotFound creates a HardwareModelDeleteEdgeNodeNotFound with default headers values
func NewHardwareModelDeleteEdgeNodeNotFound() *HardwareModelDeleteEdgeNodeNotFound {
	return &HardwareModelDeleteEdgeNodeNotFound{}
}

/*
HardwareModelDeleteEdgeNodeNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type HardwareModelDeleteEdgeNodeNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node not found response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this hardware model delete edge node not found response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node not found response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this hardware model delete edge node not found response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this hardware model delete edge node not found response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the hardware model delete edge node not found response
func (o *HardwareModelDeleteEdgeNodeNotFound) Code() int {
	return 404
}

func (o *HardwareModelDeleteEdgeNodeNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeNotFound  %+v", 404, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeNotFound) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeNotFound  %+v", 404, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeInternalServerError creates a HardwareModelDeleteEdgeNodeInternalServerError with default headers values
func NewHardwareModelDeleteEdgeNodeInternalServerError() *HardwareModelDeleteEdgeNodeInternalServerError {
	return &HardwareModelDeleteEdgeNodeInternalServerError{}
}

/*
HardwareModelDeleteEdgeNodeInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type HardwareModelDeleteEdgeNodeInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node internal server error response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this hardware model delete edge node internal server error response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node internal server error response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this hardware model delete edge node internal server error response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this hardware model delete edge node internal server error response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the hardware model delete edge node internal server error response
func (o *HardwareModelDeleteEdgeNodeInternalServerError) Code() int {
	return 500
}

func (o *HardwareModelDeleteEdgeNodeInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeInternalServerError  %+v", 500, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeInternalServerError  %+v", 500, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeGatewayTimeout creates a HardwareModelDeleteEdgeNodeGatewayTimeout with default headers values
func NewHardwareModelDeleteEdgeNodeGatewayTimeout() *HardwareModelDeleteEdgeNodeGatewayTimeout {
	return &HardwareModelDeleteEdgeNodeGatewayTimeout{}
}

/*
HardwareModelDeleteEdgeNodeGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type HardwareModelDeleteEdgeNodeGatewayTimeout struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this hardware model delete edge node gateway timeout response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this hardware model delete edge node gateway timeout response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hardware model delete edge node gateway timeout response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this hardware model delete edge node gateway timeout response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this hardware model delete edge node gateway timeout response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the hardware model delete edge node gateway timeout response
func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) Code() int {
	return 504
}

func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeGatewayTimeout  %+v", 504, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] hardwareModelDeleteEdgeNodeGatewayTimeout  %+v", 504, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteEdgeNodeDefault creates a HardwareModelDeleteEdgeNodeDefault with default headers values
func NewHardwareModelDeleteEdgeNodeDefault(code int) *HardwareModelDeleteEdgeNodeDefault {
	return &HardwareModelDeleteEdgeNodeDefault{
		_statusCode: code,
	}
}

/*
HardwareModelDeleteEdgeNodeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type HardwareModelDeleteEdgeNodeDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this hardware model delete edge node default response has a 2xx status code
func (o *HardwareModelDeleteEdgeNodeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this hardware model delete edge node default response has a 3xx status code
func (o *HardwareModelDeleteEdgeNodeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this hardware model delete edge node default response has a 4xx status code
func (o *HardwareModelDeleteEdgeNodeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this hardware model delete edge node default response has a 5xx status code
func (o *HardwareModelDeleteEdgeNodeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this hardware model delete edge node default response a status code equal to that given
func (o *HardwareModelDeleteEdgeNodeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the hardware model delete edge node default response
func (o *HardwareModelDeleteEdgeNodeDefault) Code() int {
	return o._statusCode
}

func (o *HardwareModelDeleteEdgeNodeDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] HardwareModel_DeleteEdgeNode default  %+v", o._statusCode, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/pcrtemplates/id/{id}][%d] HardwareModel_DeleteEdgeNode default  %+v", o._statusCode, o.Payload)
}

func (o *HardwareModelDeleteEdgeNodeDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *HardwareModelDeleteEdgeNodeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
