// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CEPCommonProjectReference ProjectReference represents a project that references a CEP profile
//
// swagger:model CEPCommonProjectReference
type CEPCommonProjectReference struct {

	// Project unique identifier
	ProjectID string `json:"projectId,omitempty"`

	// Project name
	ProjectName string `json:"projectName,omitempty"`
}

// Validate validates this c e p common project reference
func (m *CEPCommonProjectReference) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this c e p common project reference based on context it is used
func (m *CEPCommonProjectReference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CEPCommonProjectReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CEPCommonProjectReference) UnmarshalBinary(b []byte) error {
	var res CEPCommonProjectReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
