// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterGroupManifestJaml cluster group manifest jaml
//
// swagger:model ClusterGroupManifestJaml
type ClusterGroupManifestJaml struct {

	// The content of an jaml manifest
	YamlContent string `json:"yamlContent,omitempty"`
}

// Validate validates this cluster group manifest jaml
func (m *ClusterGroupManifestJaml) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster group manifest jaml based on context it is used
func (m *ClusterGroupManifestJaml) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterGroupManifestJaml) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterGroupManifestJaml) UnmarshalBinary(b []byte) error {
	var res ClusterGroupManifestJaml
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
