// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NtpServer NTP Server
//
// # NTP Server
//
// swagger:model NtpServer
type NtpServer struct {

	// NTP Server IP or FQDN
	Server string `json:"server,omitempty"`
}

// Validate validates this ntp server
func (m *NtpServer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ntp server based on context it is used
func (m *NtpServer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NtpServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NtpServer) UnmarshalBinary(b []byte) error {
	var res NtpServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
