// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretData Kubernetes secret data
//
// # Raw data for Kubernetes secrets including encoded credentials and SSH keys
//
// swagger:model SecretData
type SecretData struct {

	// Base64 encoded password for basic authentication, Required if Secret type is SECRET_TYPE_BASIC_AUTH
	EncodedPassword string `json:"encodedPassword,omitempty"`

	// Base64 encoded username for basic authentication, Required if Secret type is SECRET_TYPE_BASIC_AUTH
	EncodedUsername string `json:"encodedUsername,omitempty"`

	// Base64 encoded SSH private key for SSH authentication, Required if Secret type is SECRET_TYPE_SSH
	SSHPrivateKey string `json:"sshPrivateKey,omitempty"`

	// Base64 encoded SSH public key for SSH authentication, Required if Secret type is SECRET_TYPE_SSH
	SSHPublicKey string `json:"sshPublicKey,omitempty"`
}

// Validate validates this secret data
func (m *SecretData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret data based on context it is used
func (m *SecretData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretData) UnmarshalBinary(b []byte) error {
	var res SecretData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
