// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SnapshotOperationStatus Snapshot Operation Status
//
// swagger:model SnapshotOperationStatus
type SnapshotOperationStatus string

func NewSnapshotOperationStatus(value SnapshotOperationStatus) *SnapshotOperationStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated SnapshotOperationStatus.
func (m SnapshotOperationStatus) Pointer() *SnapshotOperationStatus {
	return &m
}

const (

	// SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSUNSPECIFIED captures enum value "SNAPSHOT_OPERATION_STATUS_UNSPECIFIED"
	SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSUNSPECIFIED SnapshotOperationStatus = "SNAPSHOT_OPERATION_STATUS_UNSPECIFIED"

	// SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSINPROGRESS captures enum value "SNAPSHOT_OPERATION_STATUS_IN_PROGRESS"
	SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSINPROGRESS SnapshotOperationStatus = "SNAPSHOT_OPERATION_STATUS_IN_PROGRESS"

	// SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSCOMPLETED captures enum value "SNAPSHOT_OPERATION_STATUS_COMPLETED"
	SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSCOMPLETED SnapshotOperationStatus = "SNAPSHOT_OPERATION_STATUS_COMPLETED"

	// SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSFAILED captures enum value "SNAPSHOT_OPERATION_STATUS_FAILED"
	SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSFAILED SnapshotOperationStatus = "SNAPSHOT_OPERATION_STATUS_FAILED"

	// SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSTIMEDOUT captures enum value "SNAPSHOT_OPERATION_STATUS_TIMED_OUT"
	SnapshotOperationStatusSNAPSHOTOPERATIONSTATUSTIMEDOUT SnapshotOperationStatus = "SNAPSHOT_OPERATION_STATUS_TIMED_OUT"
)

// for schema
var snapshotOperationStatusEnum []any

func init() {
	var res []SnapshotOperationStatus
	if err := json.Unmarshal([]byte(`["SNAPSHOT_OPERATION_STATUS_UNSPECIFIED","SNAPSHOT_OPERATION_STATUS_IN_PROGRESS","SNAPSHOT_OPERATION_STATUS_COMPLETED","SNAPSHOT_OPERATION_STATUS_FAILED","SNAPSHOT_OPERATION_STATUS_TIMED_OUT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		snapshotOperationStatusEnum = append(snapshotOperationStatusEnum, v)
	}
}

func (m SnapshotOperationStatus) validateSnapshotOperationStatusEnum(path, location string, value SnapshotOperationStatus) error {
	if err := validate.EnumCase(path, location, value, snapshotOperationStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this snapshot operation status
func (m SnapshotOperationStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSnapshotOperationStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this snapshot operation status based on context it is used
func (m SnapshotOperationStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
