// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZksInstanceRegistrationInfo zks instance registration info
//
// swagger:model ZksInstanceRegistrationInfo
type ZksInstanceRegistrationInfo struct {

	// Registration commands for the ZKS instance
	Commands *ZksInstanceRegistrationCommands `json:"commands,omitempty"`

	// Timestamp when the registration commands were created
	Created string `json:"created,omitempty"`

	// URL to fetch the registration manifest
	ManifestURL string `json:"manifestUrl,omitempty"`
}

// Validate validates this zks instance registration info
func (m *ZksInstanceRegistrationInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommands(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZksInstanceRegistrationInfo) validateCommands(formats strfmt.Registry) error {
	if swag.IsZero(m.Commands) { // not required
		return nil
	}

	if m.Commands != nil {
		if err := m.Commands.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("commands")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("commands")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this zks instance registration info based on the context it is used
func (m *ZksInstanceRegistrationInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCommands(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZksInstanceRegistrationInfo) contextValidateCommands(ctx context.Context, formats strfmt.Registry) error {

	if m.Commands != nil {

		if swag.IsZero(m.Commands) { // not required
			return nil
		}

		if err := m.Commands.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("commands")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("commands")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ZksInstanceRegistrationInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZksInstanceRegistrationInfo) UnmarshalBinary(b []byte) error {
	var res ZksInstanceRegistrationInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
