// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZserviceAssetGroupDeploymentCreateResponse DeploymentCreateResponse - refers to the response object for deployment create
//
// swagger:model zservice_asset_groupDeploymentCreateResponse
type ZserviceAssetGroupDeploymentCreateResponse struct {

	// deployment Id
	DeploymentID string `json:"deploymentId,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// workflow info
	WorkflowInfo []*ZserviceAssetGroupWorkflowInfo `json:"workflowInfo"`
}

// Validate validates this zservice asset group deployment create response
func (m *ZserviceAssetGroupDeploymentCreateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkflowInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZserviceAssetGroupDeploymentCreateResponse) validateWorkflowInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.WorkflowInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.WorkflowInfo); i++ {
		if swag.IsZero(m.WorkflowInfo[i]) { // not required
			continue
		}

		if m.WorkflowInfo[i] != nil {
			if err := m.WorkflowInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("workflowInfo" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("workflowInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this zservice asset group deployment create response based on the context it is used
func (m *ZserviceAssetGroupDeploymentCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWorkflowInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZserviceAssetGroupDeploymentCreateResponse) contextValidateWorkflowInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.WorkflowInfo); i++ {

		if m.WorkflowInfo[i] != nil {

			if swag.IsZero(m.WorkflowInfo[i]) { // not required
				return nil
			}

			if err := m.WorkflowInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("workflowInfo" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("workflowInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ZserviceAssetGroupDeploymentCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZserviceAssetGroupDeploymentCreateResponse) UnmarshalBinary(b []byte) error {
	var res ZserviceAssetGroupDeploymentCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
