// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZserviceAssetGroupCreateResponse AssetGroupCreateResponse - refers to response object for creating asset group
//
// swagger:model zserviceAssetGroupCreateResponse
type ZserviceAssetGroupCreateResponse struct {

	// asset group Id
	AssetGroupID string `json:"assetGroupId,omitempty"`

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this zservice asset group create response
func (m *ZserviceAssetGroupCreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this zservice asset group create response based on context it is used
func (m *ZserviceAssetGroupCreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZserviceAssetGroupCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZserviceAssetGroupCreateResponse) UnmarshalBinary(b []byte) error {
	var res ZserviceAssetGroupCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
