// Code generated by go-swagger; DO NOT EDIT.

package kubernetes_deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider-zedcloud/v2/models"
)

// NewUpdateDeploymentParams creates a new UpdateDeploymentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDeploymentParams() *UpdateDeploymentParams {
	return &UpdateDeploymentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDeploymentParamsWithTimeout creates a new UpdateDeploymentParams object
// with the ability to set a timeout on a request.
func NewUpdateDeploymentParamsWithTimeout(timeout time.Duration) *UpdateDeploymentParams {
	return &UpdateDeploymentParams{
		timeout: timeout,
	}
}

// NewUpdateDeploymentParamsWithContext creates a new UpdateDeploymentParams object
// with the ability to set a context for a request.
func NewUpdateDeploymentParamsWithContext(ctx context.Context) *UpdateDeploymentParams {
	return &UpdateDeploymentParams{
		Context: ctx,
	}
}

// NewUpdateDeploymentParamsWithHTTPClient creates a new UpdateDeploymentParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDeploymentParamsWithHTTPClient(client *http.Client) *UpdateDeploymentParams {
	return &UpdateDeploymentParams{
		HTTPClient: client,
	}
}

/*
UpdateDeploymentParams contains all the parameters to send to the API endpoint

	for the kubernetes deployments update deployment operation.

	Typically these are written to a http.Request.
*/
type UpdateDeploymentParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	/* Body.

	   Updated deployment configuration (required)
	*/
	Body *models.DeploymentRequest

	/* DeploymentID.

	   Unique identifier of the deployment to update (required). Example: 'dep-abc123'
	*/
	DeploymentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the kubernetes deployments update deployment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDeploymentParams) WithDefaults() *UpdateDeploymentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kubernetes deployments update deployment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDeploymentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithTimeout(timeout time.Duration) *UpdateDeploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithContext(ctx context.Context) *UpdateDeploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithHTTPClient(client *http.Client) *UpdateDeploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithXRequestID(xRequestID *string) *UpdateDeploymentParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithBody(body *models.DeploymentRequest) *UpdateDeploymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetBody(body *models.DeploymentRequest) {
	o.Body = body
}

// WithDeploymentID adds the deploymentID to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) WithDeploymentID(deploymentID string) *UpdateDeploymentParams {
	o.SetDeploymentID(deploymentID)
	return o
}

// SetDeploymentID adds the deploymentId to the kubernetes deployments update deployment params
func (o *UpdateDeploymentParams) SetDeploymentID(deploymentID string) {
	o.DeploymentID = deploymentID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDeploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param deploymentId
	if err := r.SetPathParam("deploymentId", o.DeploymentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
