// Code generated by go-swagger; DO NOT EDIT.

package z_asset_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider-zedcloud/v2/models"
)

// ZAssetGroupsDeleteAssetGroupReader is a Reader for the ZAssetGroupsDeleteAssetGroup structure.
type ZAssetGroupsDeleteAssetGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ZAssetGroupsDeleteAssetGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewZAssetGroupsDeleteAssetGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewZAssetGroupsDeleteAssetGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewZAssetGroupsDeleteAssetGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewZAssetGroupsDeleteAssetGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewZAssetGroupsDeleteAssetGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewZAssetGroupsDeleteAssetGroupGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewZAssetGroupsDeleteAssetGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewZAssetGroupsDeleteAssetGroupOK creates a ZAssetGroupsDeleteAssetGroupOK with default headers values
func NewZAssetGroupsDeleteAssetGroupOK() *ZAssetGroupsDeleteAssetGroupOK {
	return &ZAssetGroupsDeleteAssetGroupOK{}
}

/*
ZAssetGroupsDeleteAssetGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type ZAssetGroupsDeleteAssetGroupOK struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group o k response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this z asset groups delete asset group o k response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group o k response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this z asset groups delete asset group o k response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this z asset groups delete asset group o k response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the z asset groups delete asset group o k response
func (o *ZAssetGroupsDeleteAssetGroupOK) Code() int {
	return 200
}

func (o *ZAssetGroupsDeleteAssetGroupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupOK %s", 200, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupOK %s", 200, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupOK) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupUnauthorized creates a ZAssetGroupsDeleteAssetGroupUnauthorized with default headers values
func NewZAssetGroupsDeleteAssetGroupUnauthorized() *ZAssetGroupsDeleteAssetGroupUnauthorized {
	return &ZAssetGroupsDeleteAssetGroupUnauthorized{}
}

/*
ZAssetGroupsDeleteAssetGroupUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type ZAssetGroupsDeleteAssetGroupUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group unauthorized response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z asset groups delete asset group unauthorized response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group unauthorized response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this z asset groups delete asset group unauthorized response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this z asset groups delete asset group unauthorized response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the z asset groups delete asset group unauthorized response
func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) Code() int {
	return 401
}

func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupUnauthorized %s", 401, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupUnauthorized %s", 401, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupForbidden creates a ZAssetGroupsDeleteAssetGroupForbidden with default headers values
func NewZAssetGroupsDeleteAssetGroupForbidden() *ZAssetGroupsDeleteAssetGroupForbidden {
	return &ZAssetGroupsDeleteAssetGroupForbidden{}
}

/*
ZAssetGroupsDeleteAssetGroupForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have application level access permission for the operation or does not have access scope to the project.
*/
type ZAssetGroupsDeleteAssetGroupForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group forbidden response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z asset groups delete asset group forbidden response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group forbidden response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this z asset groups delete asset group forbidden response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this z asset groups delete asset group forbidden response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the z asset groups delete asset group forbidden response
func (o *ZAssetGroupsDeleteAssetGroupForbidden) Code() int {
	return 403
}

func (o *ZAssetGroupsDeleteAssetGroupForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupForbidden %s", 403, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupForbidden %s", 403, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupNotFound creates a ZAssetGroupsDeleteAssetGroupNotFound with default headers values
func NewZAssetGroupsDeleteAssetGroupNotFound() *ZAssetGroupsDeleteAssetGroupNotFound {
	return &ZAssetGroupsDeleteAssetGroupNotFound{}
}

/*
ZAssetGroupsDeleteAssetGroupNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type ZAssetGroupsDeleteAssetGroupNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group not found response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z asset groups delete asset group not found response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group not found response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this z asset groups delete asset group not found response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this z asset groups delete asset group not found response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the z asset groups delete asset group not found response
func (o *ZAssetGroupsDeleteAssetGroupNotFound) Code() int {
	return 404
}

func (o *ZAssetGroupsDeleteAssetGroupNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupNotFound %s", 404, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupNotFound %s", 404, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupInternalServerError creates a ZAssetGroupsDeleteAssetGroupInternalServerError with default headers values
func NewZAssetGroupsDeleteAssetGroupInternalServerError() *ZAssetGroupsDeleteAssetGroupInternalServerError {
	return &ZAssetGroupsDeleteAssetGroupInternalServerError{}
}

/*
ZAssetGroupsDeleteAssetGroupInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type ZAssetGroupsDeleteAssetGroupInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group internal server error response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z asset groups delete asset group internal server error response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group internal server error response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this z asset groups delete asset group internal server error response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this z asset groups delete asset group internal server error response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the z asset groups delete asset group internal server error response
func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) Code() int {
	return 500
}

func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupInternalServerError %s", 500, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupInternalServerError %s", 500, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupGatewayTimeout creates a ZAssetGroupsDeleteAssetGroupGatewayTimeout with default headers values
func NewZAssetGroupsDeleteAssetGroupGatewayTimeout() *ZAssetGroupsDeleteAssetGroupGatewayTimeout {
	return &ZAssetGroupsDeleteAssetGroupGatewayTimeout{}
}

/*
ZAssetGroupsDeleteAssetGroupGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type ZAssetGroupsDeleteAssetGroupGatewayTimeout struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z asset groups delete asset group gateway timeout response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z asset groups delete asset group gateway timeout response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z asset groups delete asset group gateway timeout response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this z asset groups delete asset group gateway timeout response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this z asset groups delete asset group gateway timeout response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the z asset groups delete asset group gateway timeout response
func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) Code() int {
	return 504
}

func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupGatewayTimeout %s", 504, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] zAssetGroupsDeleteAssetGroupGatewayTimeout %s", 504, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewZAssetGroupsDeleteAssetGroupDefault creates a ZAssetGroupsDeleteAssetGroupDefault with default headers values
func NewZAssetGroupsDeleteAssetGroupDefault(code int) *ZAssetGroupsDeleteAssetGroupDefault {
	return &ZAssetGroupsDeleteAssetGroupDefault{
		_statusCode: code,
	}
}

/*
ZAssetGroupsDeleteAssetGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ZAssetGroupsDeleteAssetGroupDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this z asset groups delete asset group default response has a 2xx status code
func (o *ZAssetGroupsDeleteAssetGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this z asset groups delete asset group default response has a 3xx status code
func (o *ZAssetGroupsDeleteAssetGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this z asset groups delete asset group default response has a 4xx status code
func (o *ZAssetGroupsDeleteAssetGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this z asset groups delete asset group default response has a 5xx status code
func (o *ZAssetGroupsDeleteAssetGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this z asset groups delete asset group default response a status code equal to that given
func (o *ZAssetGroupsDeleteAssetGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the z asset groups delete asset group default response
func (o *ZAssetGroupsDeleteAssetGroupDefault) Code() int {
	return o._statusCode
}

func (o *ZAssetGroupsDeleteAssetGroupDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] ZAssetGroups_DeleteAssetGroup default %s", o._statusCode, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/asset-groups/id/{id}][%d] ZAssetGroups_DeleteAssetGroup default %s", o._statusCode, payload)
}

func (o *ZAssetGroupsDeleteAssetGroupDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ZAssetGroupsDeleteAssetGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
