// Code generated by go-swagger; DO NOT EDIT.

package z_k_s_cluster_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider-zedcloud/v2/models"
)

// BulkUpgradeK3sReader is a Reader for the BulkUpgradeK3s structure.
type BulkUpgradeK3sReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkUpgradeK3sReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewBulkUpgradeK3sOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBulkUpgradeK3sBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewBulkUpgradeK3sUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBulkUpgradeK3sForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBulkUpgradeK3sNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewBulkUpgradeK3sConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkUpgradeK3sInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewBulkUpgradeK3sDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBulkUpgradeK3sOK creates a BulkUpgradeK3sOK with default headers values
func NewBulkUpgradeK3sOK() *BulkUpgradeK3sOK {
	return &BulkUpgradeK3sOK{}
}

/*
BulkUpgradeK3sOK describes a response with status code 200, with default header values.

Successfully initiated K3s upgrade
*/
type BulkUpgradeK3sOK struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s o k response has a 2xx status code
func (o *BulkUpgradeK3sOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s o k response has a 3xx status code
func (o *BulkUpgradeK3sOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s o k response has a 4xx status code
func (o *BulkUpgradeK3sOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s o k response has a 5xx status code
func (o *BulkUpgradeK3sOK) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s o k response a status code equal to that given
func (o *BulkUpgradeK3sOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s o k response
func (o *BulkUpgradeK3sOK) Code() int {
	return 200
}

func (o *BulkUpgradeK3sOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sOK %s", 200, payload)
}

func (o *BulkUpgradeK3sOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sOK %s", 200, payload)
}

func (o *BulkUpgradeK3sOK) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sBadRequest creates a BulkUpgradeK3sBadRequest with default headers values
func NewBulkUpgradeK3sBadRequest() *BulkUpgradeK3sBadRequest {
	return &BulkUpgradeK3sBadRequest{}
}

/*
BulkUpgradeK3sBadRequest describes a response with status code 400, with default header values.

Bad Request. Invalid upgrade configuration or empty instance IDs list.
*/
type BulkUpgradeK3sBadRequest struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s bad request response has a 2xx status code
func (o *BulkUpgradeK3sBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s bad request response has a 3xx status code
func (o *BulkUpgradeK3sBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s bad request response has a 4xx status code
func (o *BulkUpgradeK3sBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s bad request response has a 5xx status code
func (o *BulkUpgradeK3sBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s bad request response a status code equal to that given
func (o *BulkUpgradeK3sBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s bad request response
func (o *BulkUpgradeK3sBadRequest) Code() int {
	return 400
}

func (o *BulkUpgradeK3sBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sBadRequest %s", 400, payload)
}

func (o *BulkUpgradeK3sBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sBadRequest %s", 400, payload)
}

func (o *BulkUpgradeK3sBadRequest) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sUnauthorized creates a BulkUpgradeK3sUnauthorized with default headers values
func NewBulkUpgradeK3sUnauthorized() *BulkUpgradeK3sUnauthorized {
	return &BulkUpgradeK3sUnauthorized{}
}

/*
BulkUpgradeK3sUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication credentials are missing or invalid.
*/
type BulkUpgradeK3sUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s unauthorized response has a 2xx status code
func (o *BulkUpgradeK3sUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s unauthorized response has a 3xx status code
func (o *BulkUpgradeK3sUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s unauthorized response has a 4xx status code
func (o *BulkUpgradeK3sUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s unauthorized response has a 5xx status code
func (o *BulkUpgradeK3sUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s unauthorized response a status code equal to that given
func (o *BulkUpgradeK3sUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s unauthorized response
func (o *BulkUpgradeK3sUnauthorized) Code() int {
	return 401
}

func (o *BulkUpgradeK3sUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sUnauthorized %s", 401, payload)
}

func (o *BulkUpgradeK3sUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sUnauthorized %s", 401, payload)
}

func (o *BulkUpgradeK3sUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sForbidden creates a BulkUpgradeK3sForbidden with default headers values
func NewBulkUpgradeK3sForbidden() *BulkUpgradeK3sForbidden {
	return &BulkUpgradeK3sForbidden{}
}

/*
BulkUpgradeK3sForbidden describes a response with status code 403, with default header values.

Forbidden. User does not have permission to upgrade ZKS instances.
*/
type BulkUpgradeK3sForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s forbidden response has a 2xx status code
func (o *BulkUpgradeK3sForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s forbidden response has a 3xx status code
func (o *BulkUpgradeK3sForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s forbidden response has a 4xx status code
func (o *BulkUpgradeK3sForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s forbidden response has a 5xx status code
func (o *BulkUpgradeK3sForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s forbidden response a status code equal to that given
func (o *BulkUpgradeK3sForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s forbidden response
func (o *BulkUpgradeK3sForbidden) Code() int {
	return 403
}

func (o *BulkUpgradeK3sForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sForbidden %s", 403, payload)
}

func (o *BulkUpgradeK3sForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sForbidden %s", 403, payload)
}

func (o *BulkUpgradeK3sForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sNotFound creates a BulkUpgradeK3sNotFound with default headers values
func NewBulkUpgradeK3sNotFound() *BulkUpgradeK3sNotFound {
	return &BulkUpgradeK3sNotFound{}
}

/*
BulkUpgradeK3sNotFound describes a response with status code 404, with default header values.

Not Found. One or more ZKS instances with the specified IDs do not exist.
*/
type BulkUpgradeK3sNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s not found response has a 2xx status code
func (o *BulkUpgradeK3sNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s not found response has a 3xx status code
func (o *BulkUpgradeK3sNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s not found response has a 4xx status code
func (o *BulkUpgradeK3sNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s not found response has a 5xx status code
func (o *BulkUpgradeK3sNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s not found response a status code equal to that given
func (o *BulkUpgradeK3sNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s not found response
func (o *BulkUpgradeK3sNotFound) Code() int {
	return 404
}

func (o *BulkUpgradeK3sNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sNotFound %s", 404, payload)
}

func (o *BulkUpgradeK3sNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sNotFound %s", 404, payload)
}

func (o *BulkUpgradeK3sNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sConflict creates a BulkUpgradeK3sConflict with default headers values
func NewBulkUpgradeK3sConflict() *BulkUpgradeK3sConflict {
	return &BulkUpgradeK3sConflict{}
}

/*
BulkUpgradeK3sConflict describes a response with status code 409, with default header values.

Conflict. Cannot upgrade due to cluster state or ongoing operations.
*/
type BulkUpgradeK3sConflict struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s conflict response has a 2xx status code
func (o *BulkUpgradeK3sConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s conflict response has a 3xx status code
func (o *BulkUpgradeK3sConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s conflict response has a 4xx status code
func (o *BulkUpgradeK3sConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s conflict response has a 5xx status code
func (o *BulkUpgradeK3sConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s conflict response a status code equal to that given
func (o *BulkUpgradeK3sConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s conflict response
func (o *BulkUpgradeK3sConflict) Code() int {
	return 409
}

func (o *BulkUpgradeK3sConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sConflict %s", 409, payload)
}

func (o *BulkUpgradeK3sConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sConflict %s", 409, payload)
}

func (o *BulkUpgradeK3sConflict) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sInternalServerError creates a BulkUpgradeK3sInternalServerError with default headers values
func NewBulkUpgradeK3sInternalServerError() *BulkUpgradeK3sInternalServerError {
	return &BulkUpgradeK3sInternalServerError{}
}

/*
BulkUpgradeK3sInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Failed to initiate K3s upgrade due to server error.
*/
type BulkUpgradeK3sInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s internal server error response has a 2xx status code
func (o *BulkUpgradeK3sInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s internal server error response has a 3xx status code
func (o *BulkUpgradeK3sInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s internal server error response has a 4xx status code
func (o *BulkUpgradeK3sInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s internal server error response has a 5xx status code
func (o *BulkUpgradeK3sInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s internal server error response a status code equal to that given
func (o *BulkUpgradeK3sInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s internal server error response
func (o *BulkUpgradeK3sInternalServerError) Code() int {
	return 500
}

func (o *BulkUpgradeK3sInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sInternalServerError %s", 500, payload)
}

func (o *BulkUpgradeK3sInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] zKSClusterInstancesBulkUpgradeK3sInternalServerError %s", 500, payload)
}

func (o *BulkUpgradeK3sInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *BulkUpgradeK3sInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkUpgradeK3sDefault creates a BulkUpgradeK3sDefault with default headers values
func NewBulkUpgradeK3sDefault(code int) *BulkUpgradeK3sDefault {
	return &BulkUpgradeK3sDefault{
		_statusCode: code,
	}
}

/*
BulkUpgradeK3sDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type BulkUpgradeK3sDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this z k s cluster instances bulk upgrade k3s default response has a 2xx status code
func (o *BulkUpgradeK3sDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this z k s cluster instances bulk upgrade k3s default response has a 3xx status code
func (o *BulkUpgradeK3sDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this z k s cluster instances bulk upgrade k3s default response has a 4xx status code
func (o *BulkUpgradeK3sDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this z k s cluster instances bulk upgrade k3s default response has a 5xx status code
func (o *BulkUpgradeK3sDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this z k s cluster instances bulk upgrade k3s default response a status code equal to that given
func (o *BulkUpgradeK3sDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the z k s cluster instances bulk upgrade k3s default response
func (o *BulkUpgradeK3sDefault) Code() int {
	return o._statusCode
}

func (o *BulkUpgradeK3sDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] _BulkUpgradeK3s default %s", o._statusCode, payload)
}

func (o *BulkUpgradeK3sDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/zks/instances/k3s-upgrade][%d] _BulkUpgradeK3s default %s", o._statusCode, payload)
}

func (o *BulkUpgradeK3sDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *BulkUpgradeK3sDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
