// Code generated by go-swagger; DO NOT EDIT.

package z_k_s_cluster_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider-zedcloud/v2/models"
)

// GetZKSInstanceMetricsReader is a Reader for the GetZKSInstanceMetrics structure.
type GetZKSInstanceMetricsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZKSInstanceMetricsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetZKSInstanceMetricsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetZKSInstanceMetricsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetZKSInstanceMetricsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetZKSInstanceMetricsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetZKSInstanceMetricsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetZKSInstanceMetricsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetZKSInstanceMetricsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetZKSInstanceMetricsOK creates a GetZKSInstanceMetricsOK with default headers values
func NewGetZKSInstanceMetricsOK() *GetZKSInstanceMetricsOK {
	return &GetZKSInstanceMetricsOK{}
}

/*
GetZKSInstanceMetricsOK describes a response with status code 200, with default header values.

Successfully retrieved ZKS instance metrics
*/
type GetZKSInstanceMetricsOK struct {
	Payload *models.ZksInstanceMetrics
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics o k response has a 2xx status code
func (o *GetZKSInstanceMetricsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics o k response has a 3xx status code
func (o *GetZKSInstanceMetricsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics o k response has a 4xx status code
func (o *GetZKSInstanceMetricsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics o k response has a 5xx status code
func (o *GetZKSInstanceMetricsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics o k response a status code equal to that given
func (o *GetZKSInstanceMetricsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics o k response
func (o *GetZKSInstanceMetricsOK) Code() int {
	return 200
}

func (o *GetZKSInstanceMetricsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsOK %s", 200, payload)
}

func (o *GetZKSInstanceMetricsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsOK %s", 200, payload)
}

func (o *GetZKSInstanceMetricsOK) GetPayload() *models.ZksInstanceMetrics {
	return o.Payload
}

func (o *GetZKSInstanceMetricsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZksInstanceMetrics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsBadRequest creates a GetZKSInstanceMetricsBadRequest with default headers values
func NewGetZKSInstanceMetricsBadRequest() *GetZKSInstanceMetricsBadRequest {
	return &GetZKSInstanceMetricsBadRequest{}
}

/*
GetZKSInstanceMetricsBadRequest describes a response with status code 400, with default header values.

Bad Request. Invalid ZKS instance ID format.
*/
type GetZKSInstanceMetricsBadRequest struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics bad request response has a 2xx status code
func (o *GetZKSInstanceMetricsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics bad request response has a 3xx status code
func (o *GetZKSInstanceMetricsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics bad request response has a 4xx status code
func (o *GetZKSInstanceMetricsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics bad request response has a 5xx status code
func (o *GetZKSInstanceMetricsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics bad request response a status code equal to that given
func (o *GetZKSInstanceMetricsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics bad request response
func (o *GetZKSInstanceMetricsBadRequest) Code() int {
	return 400
}

func (o *GetZKSInstanceMetricsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsBadRequest %s", 400, payload)
}

func (o *GetZKSInstanceMetricsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsBadRequest %s", 400, payload)
}

func (o *GetZKSInstanceMetricsBadRequest) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetZKSInstanceMetricsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsUnauthorized creates a GetZKSInstanceMetricsUnauthorized with default headers values
func NewGetZKSInstanceMetricsUnauthorized() *GetZKSInstanceMetricsUnauthorized {
	return &GetZKSInstanceMetricsUnauthorized{}
}

/*
GetZKSInstanceMetricsUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication credentials are missing or invalid.
*/
type GetZKSInstanceMetricsUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics unauthorized response has a 2xx status code
func (o *GetZKSInstanceMetricsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics unauthorized response has a 3xx status code
func (o *GetZKSInstanceMetricsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics unauthorized response has a 4xx status code
func (o *GetZKSInstanceMetricsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics unauthorized response has a 5xx status code
func (o *GetZKSInstanceMetricsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics unauthorized response a status code equal to that given
func (o *GetZKSInstanceMetricsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics unauthorized response
func (o *GetZKSInstanceMetricsUnauthorized) Code() int {
	return 401
}

func (o *GetZKSInstanceMetricsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsUnauthorized %s", 401, payload)
}

func (o *GetZKSInstanceMetricsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsUnauthorized %s", 401, payload)
}

func (o *GetZKSInstanceMetricsUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetZKSInstanceMetricsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsForbidden creates a GetZKSInstanceMetricsForbidden with default headers values
func NewGetZKSInstanceMetricsForbidden() *GetZKSInstanceMetricsForbidden {
	return &GetZKSInstanceMetricsForbidden{}
}

/*
GetZKSInstanceMetricsForbidden describes a response with status code 403, with default header values.

Forbidden. User does not have permission to view metrics for this ZKS instance.
*/
type GetZKSInstanceMetricsForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics forbidden response has a 2xx status code
func (o *GetZKSInstanceMetricsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics forbidden response has a 3xx status code
func (o *GetZKSInstanceMetricsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics forbidden response has a 4xx status code
func (o *GetZKSInstanceMetricsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics forbidden response has a 5xx status code
func (o *GetZKSInstanceMetricsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics forbidden response a status code equal to that given
func (o *GetZKSInstanceMetricsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics forbidden response
func (o *GetZKSInstanceMetricsForbidden) Code() int {
	return 403
}

func (o *GetZKSInstanceMetricsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsForbidden %s", 403, payload)
}

func (o *GetZKSInstanceMetricsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsForbidden %s", 403, payload)
}

func (o *GetZKSInstanceMetricsForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetZKSInstanceMetricsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsNotFound creates a GetZKSInstanceMetricsNotFound with default headers values
func NewGetZKSInstanceMetricsNotFound() *GetZKSInstanceMetricsNotFound {
	return &GetZKSInstanceMetricsNotFound{}
}

/*
GetZKSInstanceMetricsNotFound describes a response with status code 404, with default header values.

Not Found. ZKS instance with the specified ID does not exist.
*/
type GetZKSInstanceMetricsNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics not found response has a 2xx status code
func (o *GetZKSInstanceMetricsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics not found response has a 3xx status code
func (o *GetZKSInstanceMetricsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics not found response has a 4xx status code
func (o *GetZKSInstanceMetricsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics not found response has a 5xx status code
func (o *GetZKSInstanceMetricsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics not found response a status code equal to that given
func (o *GetZKSInstanceMetricsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics not found response
func (o *GetZKSInstanceMetricsNotFound) Code() int {
	return 404
}

func (o *GetZKSInstanceMetricsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsNotFound %s", 404, payload)
}

func (o *GetZKSInstanceMetricsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsNotFound %s", 404, payload)
}

func (o *GetZKSInstanceMetricsNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetZKSInstanceMetricsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsInternalServerError creates a GetZKSInstanceMetricsInternalServerError with default headers values
func NewGetZKSInstanceMetricsInternalServerError() *GetZKSInstanceMetricsInternalServerError {
	return &GetZKSInstanceMetricsInternalServerError{}
}

/*
GetZKSInstanceMetricsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Failed to retrieve metrics due to server error.
*/
type GetZKSInstanceMetricsInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics internal server error response has a 2xx status code
func (o *GetZKSInstanceMetricsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics internal server error response has a 3xx status code
func (o *GetZKSInstanceMetricsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics internal server error response has a 4xx status code
func (o *GetZKSInstanceMetricsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics internal server error response has a 5xx status code
func (o *GetZKSInstanceMetricsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics internal server error response a status code equal to that given
func (o *GetZKSInstanceMetricsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics internal server error response
func (o *GetZKSInstanceMetricsInternalServerError) Code() int {
	return 500
}

func (o *GetZKSInstanceMetricsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsInternalServerError %s", 500, payload)
}

func (o *GetZKSInstanceMetricsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] zKSClusterInstancesGetZKSInstanceMetricsInternalServerError %s", 500, payload)
}

func (o *GetZKSInstanceMetricsInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetZKSInstanceMetricsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetZKSInstanceMetricsDefault creates a GetZKSInstanceMetricsDefault with default headers values
func NewGetZKSInstanceMetricsDefault(code int) *GetZKSInstanceMetricsDefault {
	return &GetZKSInstanceMetricsDefault{
		_statusCode: code,
	}
}

/*
GetZKSInstanceMetricsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetZKSInstanceMetricsDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this z k s cluster instances get z k s instance metrics default response has a 2xx status code
func (o *GetZKSInstanceMetricsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this z k s cluster instances get z k s instance metrics default response has a 3xx status code
func (o *GetZKSInstanceMetricsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this z k s cluster instances get z k s instance metrics default response has a 4xx status code
func (o *GetZKSInstanceMetricsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this z k s cluster instances get z k s instance metrics default response has a 5xx status code
func (o *GetZKSInstanceMetricsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this z k s cluster instances get z k s instance metrics default response a status code equal to that given
func (o *GetZKSInstanceMetricsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the z k s cluster instances get z k s instance metrics default response
func (o *GetZKSInstanceMetricsDefault) Code() int {
	return o._statusCode
}

func (o *GetZKSInstanceMetricsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] _GetZKSInstanceMetrics default %s", o._statusCode, payload)
}

func (o *GetZKSInstanceMetricsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/zks/instances/id/{zksId}/metrics][%d] _GetZKSInstanceMetrics default %s", o._statusCode, payload)
}

func (o *GetZKSInstanceMetricsDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *GetZKSInstanceMetricsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
