// Code generated by go-swagger; DO NOT EDIT.

package hardware_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGlobalHardwareBrandByNameParams creates a new GetGlobalHardwareBrandByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGlobalHardwareBrandByNameParams() *GetGlobalHardwareBrandByNameParams {
	return &GetGlobalHardwareBrandByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGlobalHardwareBrandByNameParamsWithTimeout creates a new GetGlobalHardwareBrandByNameParams object
// with the ability to set a timeout on a request.
func NewGetGlobalHardwareBrandByNameParamsWithTimeout(timeout time.Duration) *GetGlobalHardwareBrandByNameParams {
	return &GetGlobalHardwareBrandByNameParams{
		timeout: timeout,
	}
}

// NewGetGlobalHardwareBrandByNameParamsWithContext creates a new GetGlobalHardwareBrandByNameParams object
// with the ability to set a context for a request.
func NewGetGlobalHardwareBrandByNameParamsWithContext(ctx context.Context) *GetGlobalHardwareBrandByNameParams {
	return &GetGlobalHardwareBrandByNameParams{
		Context: ctx,
	}
}

// NewGetGlobalHardwareBrandByNameParamsWithHTTPClient creates a new GetGlobalHardwareBrandByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGlobalHardwareBrandByNameParamsWithHTTPClient(client *http.Client) *GetGlobalHardwareBrandByNameParams {
	return &GetGlobalHardwareBrandByNameParams{
		HTTPClient: client,
	}
}

/*
GetGlobalHardwareBrandByNameParams contains all the parameters to send to the API endpoint

	for the get global hardware brand by name operation.

	Typically these are written to a http.Request.
*/
type GetGlobalHardwareBrandByNameParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	/* EnterpriseID.

	   deprecated field: EnterpriseId
	*/
	EnterpriseID *string

	/* Name.

	   user defined sys brand name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get global hardware brand by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalHardwareBrandByNameParams) WithDefaults() *GetGlobalHardwareBrandByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get global hardware brand by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalHardwareBrandByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithTimeout(timeout time.Duration) *GetGlobalHardwareBrandByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithContext(ctx context.Context) *GetGlobalHardwareBrandByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithHTTPClient(client *http.Client) *GetGlobalHardwareBrandByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithXRequestID(xRequestID *string) *GetGlobalHardwareBrandByNameParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithEnterpriseID adds the enterpriseID to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithEnterpriseID(enterpriseID *string) *GetGlobalHardwareBrandByNameParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetEnterpriseID(enterpriseID *string) {
	o.EnterpriseID = enterpriseID
}

// WithName adds the name to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) WithName(name string) *GetGlobalHardwareBrandByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get global hardware brand by name params
func (o *GetGlobalHardwareBrandByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetGlobalHardwareBrandByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.EnterpriseID != nil {

		// query param enterpriseId
		var qrEnterpriseID string

		if o.EnterpriseID != nil {
			qrEnterpriseID = *o.EnterpriseID
		}
		qEnterpriseID := qrEnterpriseID
		if qEnterpriseID != "" {

			if err := r.SetQueryParam("enterpriseId", qEnterpriseID); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
