// Code generated by go-swagger; DO NOT EDIT.

package hardware_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider/models"
)

// GetGlobalHardwareBrandByNameReader is a Reader for the GetGlobalHardwareBrandByName structure.
type GetGlobalHardwareBrandByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGlobalHardwareBrandByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGlobalHardwareBrandByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetGlobalHardwareBrandByNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetGlobalHardwareBrandByNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGlobalHardwareBrandByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGlobalHardwareBrandByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetGlobalHardwareBrandByNameGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGlobalHardwareBrandByNameOK creates a GetGlobalHardwareBrandByNameOK with default headers values
func NewGetGlobalHardwareBrandByNameOK() *GetGlobalHardwareBrandByNameOK {
	return &GetGlobalHardwareBrandByNameOK{}
}

/*
GetGlobalHardwareBrandByNameOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetGlobalHardwareBrandByNameOK struct {
	Payload *models.SysBrand
}

// IsSuccess returns true when this get global hardware brand by name o k response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get global hardware brand by name o k response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name o k response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get global hardware brand by name o k response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get global hardware brand by name o k response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetGlobalHardwareBrandByNameOK) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameOK  %+v", 200, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameOK) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameOK  %+v", 200, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameOK) GetPayload() *models.SysBrand {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SysBrand)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlobalHardwareBrandByNameUnauthorized creates a GetGlobalHardwareBrandByNameUnauthorized with default headers values
func NewGetGlobalHardwareBrandByNameUnauthorized() *GetGlobalHardwareBrandByNameUnauthorized {
	return &GetGlobalHardwareBrandByNameUnauthorized{}
}

/*
GetGlobalHardwareBrandByNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type GetGlobalHardwareBrandByNameUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this get global hardware brand by name unauthorized response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get global hardware brand by name unauthorized response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name unauthorized response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get global hardware brand by name unauthorized response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get global hardware brand by name unauthorized response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetGlobalHardwareBrandByNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameUnauthorized  %+v", 401, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameUnauthorized  %+v", 401, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlobalHardwareBrandByNameForbidden creates a GetGlobalHardwareBrandByNameForbidden with default headers values
func NewGetGlobalHardwareBrandByNameForbidden() *GetGlobalHardwareBrandByNameForbidden {
	return &GetGlobalHardwareBrandByNameForbidden{}
}

/*
GetGlobalHardwareBrandByNameForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type GetGlobalHardwareBrandByNameForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this get global hardware brand by name forbidden response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get global hardware brand by name forbidden response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name forbidden response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get global hardware brand by name forbidden response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get global hardware brand by name forbidden response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetGlobalHardwareBrandByNameForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameForbidden  %+v", 403, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameForbidden) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameForbidden  %+v", 403, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlobalHardwareBrandByNameNotFound creates a GetGlobalHardwareBrandByNameNotFound with default headers values
func NewGetGlobalHardwareBrandByNameNotFound() *GetGlobalHardwareBrandByNameNotFound {
	return &GetGlobalHardwareBrandByNameNotFound{}
}

/*
GetGlobalHardwareBrandByNameNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type GetGlobalHardwareBrandByNameNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this get global hardware brand by name not found response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get global hardware brand by name not found response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name not found response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get global hardware brand by name not found response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get global hardware brand by name not found response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetGlobalHardwareBrandByNameNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameNotFound  %+v", 404, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameNotFound) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameNotFound  %+v", 404, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlobalHardwareBrandByNameInternalServerError creates a GetGlobalHardwareBrandByNameInternalServerError with default headers values
func NewGetGlobalHardwareBrandByNameInternalServerError() *GetGlobalHardwareBrandByNameInternalServerError {
	return &GetGlobalHardwareBrandByNameInternalServerError{}
}

/*
GetGlobalHardwareBrandByNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type GetGlobalHardwareBrandByNameInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this get global hardware brand by name internal server error response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get global hardware brand by name internal server error response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name internal server error response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get global hardware brand by name internal server error response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get global hardware brand by name internal server error response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetGlobalHardwareBrandByNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGlobalHardwareBrandByNameGatewayTimeout creates a GetGlobalHardwareBrandByNameGatewayTimeout with default headers values
func NewGetGlobalHardwareBrandByNameGatewayTimeout() *GetGlobalHardwareBrandByNameGatewayTimeout {
	return &GetGlobalHardwareBrandByNameGatewayTimeout{}
}

/*
GetGlobalHardwareBrandByNameGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type GetGlobalHardwareBrandByNameGatewayTimeout struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this get global hardware brand by name gateway timeout response has a 2xx status code
func (o *GetGlobalHardwareBrandByNameGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get global hardware brand by name gateway timeout response has a 3xx status code
func (o *GetGlobalHardwareBrandByNameGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get global hardware brand by name gateway timeout response has a 4xx status code
func (o *GetGlobalHardwareBrandByNameGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this get global hardware brand by name gateway timeout response has a 5xx status code
func (o *GetGlobalHardwareBrandByNameGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this get global hardware brand by name gateway timeout response a status code equal to that given
func (o *GetGlobalHardwareBrandByNameGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *GetGlobalHardwareBrandByNameGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v1/brands/global/name/{name}][%d] getGlobalHardwareBrandByNameGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetGlobalHardwareBrandByNameGatewayTimeout) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *GetGlobalHardwareBrandByNameGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
