// Code generated by go-swagger; DO NOT EDIT.

package hardware_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryHardwareModelsParams creates a new QueryHardwareModelsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryHardwareModelsParams() *QueryHardwareModelsParams {
	return &QueryHardwareModelsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryHardwareModelsParamsWithTimeout creates a new QueryHardwareModelsParams object
// with the ability to set a timeout on a request.
func NewQueryHardwareModelsParamsWithTimeout(timeout time.Duration) *QueryHardwareModelsParams {
	return &QueryHardwareModelsParams{
		timeout: timeout,
	}
}

// NewQueryHardwareModelsParamsWithContext creates a new QueryHardwareModelsParams object
// with the ability to set a context for a request.
func NewQueryHardwareModelsParamsWithContext(ctx context.Context) *QueryHardwareModelsParams {
	return &QueryHardwareModelsParams{
		Context: ctx,
	}
}

// NewQueryHardwareModelsParamsWithHTTPClient creates a new QueryHardwareModelsParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryHardwareModelsParamsWithHTTPClient(client *http.Client) *QueryHardwareModelsParams {
	return &QueryHardwareModelsParams{
		HTTPClient: client,
	}
}

/*
QueryHardwareModelsParams contains all the parameters to send to the API endpoint

	for the query hardware models operation.

	Typically these are written to a http.Request.
*/
type QueryHardwareModelsParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	/* FilterBrandID.

	   System defined universally unique Id of the brand.
	*/
	FilterBrandID *string

	/* FilterNamePattern.

	   Model name pattern to be matched.
	*/
	FilterNamePattern *string

	/* FilterOriginType.

	   origin of object - ORIGIN_UNSPECIFIED: default options, which says no Operation/Invalid Operation - ORIGIN_IMPORTED: Object imported from global enterprise. - ORIGIN_LOCAL: Objectl created locally. - ORIGIN_GLOBAL: Object created in global store,to use this type user should have root previlage.

	   Default: "ORIGIN_UNSPECIFIED"
	*/
	FilterOriginType *string

	/* NextOrderBy.

	   OrderBy helps in sorting the list response
	*/
	NextOrderBy *string

	/* NextPageNum.

	   Page Number

	   Format: int64
	*/
	NextPageNum *int64

	/* NextPageSize.

	   Defines the page size

	   Format: int64
	*/
	NextPageSize *int64

	/* NextPageToken.

	   Page Token
	*/
	NextPageToken *string

	/* NextTotalPages.

	   Total number of pages to be fetched.

	   Format: int64
	*/
	NextTotalPages *int64

	/* Summary.

	   Only summary of the records required

	   Format: boolean
	*/
	Summary *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query hardware models params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryHardwareModelsParams) WithDefaults() *QueryHardwareModelsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query hardware models params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryHardwareModelsParams) SetDefaults() {
	var (
		filterOriginTypeDefault = string("ORIGIN_UNSPECIFIED")
	)

	val := QueryHardwareModelsParams{
		FilterOriginType: &filterOriginTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the query hardware models params
func (o *QueryHardwareModelsParams) WithTimeout(timeout time.Duration) *QueryHardwareModelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query hardware models params
func (o *QueryHardwareModelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query hardware models params
func (o *QueryHardwareModelsParams) WithContext(ctx context.Context) *QueryHardwareModelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query hardware models params
func (o *QueryHardwareModelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query hardware models params
func (o *QueryHardwareModelsParams) WithHTTPClient(client *http.Client) *QueryHardwareModelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query hardware models params
func (o *QueryHardwareModelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the query hardware models params
func (o *QueryHardwareModelsParams) WithXRequestID(xRequestID *string) *QueryHardwareModelsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the query hardware models params
func (o *QueryHardwareModelsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithFilterBrandID adds the filterBrandID to the query hardware models params
func (o *QueryHardwareModelsParams) WithFilterBrandID(filterBrandID *string) *QueryHardwareModelsParams {
	o.SetFilterBrandID(filterBrandID)
	return o
}

// SetFilterBrandID adds the filterBrandId to the query hardware models params
func (o *QueryHardwareModelsParams) SetFilterBrandID(filterBrandID *string) {
	o.FilterBrandID = filterBrandID
}

// WithFilterNamePattern adds the filterNamePattern to the query hardware models params
func (o *QueryHardwareModelsParams) WithFilterNamePattern(filterNamePattern *string) *QueryHardwareModelsParams {
	o.SetFilterNamePattern(filterNamePattern)
	return o
}

// SetFilterNamePattern adds the filterNamePattern to the query hardware models params
func (o *QueryHardwareModelsParams) SetFilterNamePattern(filterNamePattern *string) {
	o.FilterNamePattern = filterNamePattern
}

// WithFilterOriginType adds the filterOriginType to the query hardware models params
func (o *QueryHardwareModelsParams) WithFilterOriginType(filterOriginType *string) *QueryHardwareModelsParams {
	o.SetFilterOriginType(filterOriginType)
	return o
}

// SetFilterOriginType adds the filterOriginType to the query hardware models params
func (o *QueryHardwareModelsParams) SetFilterOriginType(filterOriginType *string) {
	o.FilterOriginType = filterOriginType
}

// WithNextOrderBy adds the nextOrderBy to the query hardware models params
func (o *QueryHardwareModelsParams) WithNextOrderBy(nextOrderBy *string) *QueryHardwareModelsParams {
	o.SetNextOrderBy(nextOrderBy)
	return o
}

// SetNextOrderBy adds the nextOrderBy to the query hardware models params
func (o *QueryHardwareModelsParams) SetNextOrderBy(nextOrderBy *string) {
	o.NextOrderBy = nextOrderBy
}

// WithNextPageNum adds the nextPageNum to the query hardware models params
func (o *QueryHardwareModelsParams) WithNextPageNum(nextPageNum *int64) *QueryHardwareModelsParams {
	o.SetNextPageNum(nextPageNum)
	return o
}

// SetNextPageNum adds the nextPageNum to the query hardware models params
func (o *QueryHardwareModelsParams) SetNextPageNum(nextPageNum *int64) {
	o.NextPageNum = nextPageNum
}

// WithNextPageSize adds the nextPageSize to the query hardware models params
func (o *QueryHardwareModelsParams) WithNextPageSize(nextPageSize *int64) *QueryHardwareModelsParams {
	o.SetNextPageSize(nextPageSize)
	return o
}

// SetNextPageSize adds the nextPageSize to the query hardware models params
func (o *QueryHardwareModelsParams) SetNextPageSize(nextPageSize *int64) {
	o.NextPageSize = nextPageSize
}

// WithNextPageToken adds the nextPageToken to the query hardware models params
func (o *QueryHardwareModelsParams) WithNextPageToken(nextPageToken *string) *QueryHardwareModelsParams {
	o.SetNextPageToken(nextPageToken)
	return o
}

// SetNextPageToken adds the nextPageToken to the query hardware models params
func (o *QueryHardwareModelsParams) SetNextPageToken(nextPageToken *string) {
	o.NextPageToken = nextPageToken
}

// WithNextTotalPages adds the nextTotalPages to the query hardware models params
func (o *QueryHardwareModelsParams) WithNextTotalPages(nextTotalPages *int64) *QueryHardwareModelsParams {
	o.SetNextTotalPages(nextTotalPages)
	return o
}

// SetNextTotalPages adds the nextTotalPages to the query hardware models params
func (o *QueryHardwareModelsParams) SetNextTotalPages(nextTotalPages *int64) {
	o.NextTotalPages = nextTotalPages
}

// WithSummary adds the summary to the query hardware models params
func (o *QueryHardwareModelsParams) WithSummary(summary *bool) *QueryHardwareModelsParams {
	o.SetSummary(summary)
	return o
}

// SetSummary adds the summary to the query hardware models params
func (o *QueryHardwareModelsParams) SetSummary(summary *bool) {
	o.Summary = summary
}

// WriteToRequest writes these params to a swagger request
func (o *QueryHardwareModelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.FilterBrandID != nil {

		// query param filter.brandId
		var qrFilterBrandID string

		if o.FilterBrandID != nil {
			qrFilterBrandID = *o.FilterBrandID
		}
		qFilterBrandID := qrFilterBrandID
		if qFilterBrandID != "" {

			if err := r.SetQueryParam("filter.brandId", qFilterBrandID); err != nil {
				return err
			}
		}
	}

	if o.FilterNamePattern != nil {

		// query param filter.namePattern
		var qrFilterNamePattern string

		if o.FilterNamePattern != nil {
			qrFilterNamePattern = *o.FilterNamePattern
		}
		qFilterNamePattern := qrFilterNamePattern
		if qFilterNamePattern != "" {

			if err := r.SetQueryParam("filter.namePattern", qFilterNamePattern); err != nil {
				return err
			}
		}
	}

	if o.FilterOriginType != nil {

		// query param filter.originType
		var qrFilterOriginType string

		if o.FilterOriginType != nil {
			qrFilterOriginType = *o.FilterOriginType
		}
		qFilterOriginType := qrFilterOriginType
		if qFilterOriginType != "" {

			if err := r.SetQueryParam("filter.originType", qFilterOriginType); err != nil {
				return err
			}
		}
	}

	if o.NextOrderBy != nil {

		// query param next.orderBy
		var qrNextOrderBy string

		if o.NextOrderBy != nil {
			qrNextOrderBy = *o.NextOrderBy
		}
		qNextOrderBy := qrNextOrderBy
		if qNextOrderBy != "" {

			if err := r.SetQueryParam("next.orderBy", qNextOrderBy); err != nil {
				return err
			}
		}
	}

	if o.NextPageNum != nil {

		// query param next.pageNum
		var qrNextPageNum int64

		if o.NextPageNum != nil {
			qrNextPageNum = *o.NextPageNum
		}
		qNextPageNum := swag.FormatInt64(qrNextPageNum)
		if qNextPageNum != "" {

			if err := r.SetQueryParam("next.pageNum", qNextPageNum); err != nil {
				return err
			}
		}
	}

	if o.NextPageSize != nil {

		// query param next.pageSize
		var qrNextPageSize int64

		if o.NextPageSize != nil {
			qrNextPageSize = *o.NextPageSize
		}
		qNextPageSize := swag.FormatInt64(qrNextPageSize)
		if qNextPageSize != "" {

			if err := r.SetQueryParam("next.pageSize", qNextPageSize); err != nil {
				return err
			}
		}
	}

	if o.NextPageToken != nil {

		// query param next.pageToken
		var qrNextPageToken string

		if o.NextPageToken != nil {
			qrNextPageToken = *o.NextPageToken
		}
		qNextPageToken := qrNextPageToken
		if qNextPageToken != "" {

			if err := r.SetQueryParam("next.pageToken", qNextPageToken); err != nil {
				return err
			}
		}
	}

	if o.NextTotalPages != nil {

		// query param next.totalPages
		var qrNextTotalPages int64

		if o.NextTotalPages != nil {
			qrNextTotalPages = *o.NextTotalPages
		}
		qNextTotalPages := swag.FormatInt64(qrNextTotalPages)
		if qNextTotalPages != "" {

			if err := r.SetQueryParam("next.totalPages", qNextTotalPages); err != nil {
				return err
			}
		}
	}

	if o.Summary != nil {

		// query param summary
		var qrSummary bool

		if o.Summary != nil {
			qrSummary = *o.Summary
		}
		qSummary := swag.FormatBool(qrSummary)
		if qSummary != "" {

			if err := r.SetQueryParam("summary", qSummary); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
