// Code generated by go-swagger; DO NOT EDIT.

package identity_access_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/terraform-provider/models"
)

// IdentityAccessManagementUpdateCredentialReader is a Reader for the IdentityAccessManagementUpdateCredential structure.
type IdentityAccessManagementUpdateCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentityAccessManagementUpdateCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentityAccessManagementUpdateCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewIdentityAccessManagementUpdateCredentialUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewIdentityAccessManagementUpdateCredentialForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewIdentityAccessManagementUpdateCredentialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewIdentityAccessManagementUpdateCredentialConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewIdentityAccessManagementUpdateCredentialInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewIdentityAccessManagementUpdateCredentialGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIdentityAccessManagementUpdateCredentialDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentityAccessManagementUpdateCredentialOK creates a IdentityAccessManagementUpdateCredentialOK with default headers values
func NewIdentityAccessManagementUpdateCredentialOK() *IdentityAccessManagementUpdateCredentialOK {
	return &IdentityAccessManagementUpdateCredentialOK{}
}

/*
IdentityAccessManagementUpdateCredentialOK describes a response with status code 200, with default header values.

A successful response.
*/
type IdentityAccessManagementUpdateCredentialOK struct {
	Payload *models.CrudResponse
}

// IsSuccess returns true when this identity access management update credential o k response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this identity access management update credential o k response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential o k response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this identity access management update credential o k response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this identity access management update credential o k response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the identity access management update credential o k response
func (o *IdentityAccessManagementUpdateCredentialOK) Code() int {
	return 200
}

func (o *IdentityAccessManagementUpdateCredentialOK) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialOK  %+v", 200, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialOK) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialOK  %+v", 200, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialOK) GetPayload() *models.CrudResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CrudResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialUnauthorized creates a IdentityAccessManagementUpdateCredentialUnauthorized with default headers values
func NewIdentityAccessManagementUpdateCredentialUnauthorized() *IdentityAccessManagementUpdateCredentialUnauthorized {
	return &IdentityAccessManagementUpdateCredentialUnauthorized{}
}

/*
IdentityAccessManagementUpdateCredentialUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type IdentityAccessManagementUpdateCredentialUnauthorized struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential unauthorized response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential unauthorized response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential unauthorized response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this identity access management update credential unauthorized response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this identity access management update credential unauthorized response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the identity access management update credential unauthorized response
func (o *IdentityAccessManagementUpdateCredentialUnauthorized) Code() int {
	return 401
}

func (o *IdentityAccessManagementUpdateCredentialUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialUnauthorized  %+v", 401, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialUnauthorized  %+v", 401, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialUnauthorized) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialForbidden creates a IdentityAccessManagementUpdateCredentialForbidden with default headers values
func NewIdentityAccessManagementUpdateCredentialForbidden() *IdentityAccessManagementUpdateCredentialForbidden {
	return &IdentityAccessManagementUpdateCredentialForbidden{}
}

/*
IdentityAccessManagementUpdateCredentialForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type IdentityAccessManagementUpdateCredentialForbidden struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential forbidden response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential forbidden response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential forbidden response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this identity access management update credential forbidden response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this identity access management update credential forbidden response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the identity access management update credential forbidden response
func (o *IdentityAccessManagementUpdateCredentialForbidden) Code() int {
	return 403
}

func (o *IdentityAccessManagementUpdateCredentialForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialForbidden  %+v", 403, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialForbidden  %+v", 403, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialForbidden) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialNotFound creates a IdentityAccessManagementUpdateCredentialNotFound with default headers values
func NewIdentityAccessManagementUpdateCredentialNotFound() *IdentityAccessManagementUpdateCredentialNotFound {
	return &IdentityAccessManagementUpdateCredentialNotFound{}
}

/*
IdentityAccessManagementUpdateCredentialNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type IdentityAccessManagementUpdateCredentialNotFound struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential not found response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential not found response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential not found response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this identity access management update credential not found response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this identity access management update credential not found response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the identity access management update credential not found response
func (o *IdentityAccessManagementUpdateCredentialNotFound) Code() int {
	return 404
}

func (o *IdentityAccessManagementUpdateCredentialNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialNotFound  %+v", 404, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialNotFound) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialNotFound  %+v", 404, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialNotFound) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialConflict creates a IdentityAccessManagementUpdateCredentialConflict with default headers values
func NewIdentityAccessManagementUpdateCredentialConflict() *IdentityAccessManagementUpdateCredentialConflict {
	return &IdentityAccessManagementUpdateCredentialConflict{}
}

/*
IdentityAccessManagementUpdateCredentialConflict describes a response with status code 409, with default header values.

Conflict. The API gateway did not process the request because this operation will conflict with an already existing IAM credential record.
*/
type IdentityAccessManagementUpdateCredentialConflict struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential conflict response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential conflict response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential conflict response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this identity access management update credential conflict response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this identity access management update credential conflict response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the identity access management update credential conflict response
func (o *IdentityAccessManagementUpdateCredentialConflict) Code() int {
	return 409
}

func (o *IdentityAccessManagementUpdateCredentialConflict) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialConflict  %+v", 409, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialConflict) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialConflict  %+v", 409, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialConflict) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialInternalServerError creates a IdentityAccessManagementUpdateCredentialInternalServerError with default headers values
func NewIdentityAccessManagementUpdateCredentialInternalServerError() *IdentityAccessManagementUpdateCredentialInternalServerError {
	return &IdentityAccessManagementUpdateCredentialInternalServerError{}
}

/*
IdentityAccessManagementUpdateCredentialInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type IdentityAccessManagementUpdateCredentialInternalServerError struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential internal server error response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential internal server error response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential internal server error response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this identity access management update credential internal server error response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this identity access management update credential internal server error response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the identity access management update credential internal server error response
func (o *IdentityAccessManagementUpdateCredentialInternalServerError) Code() int {
	return 500
}

func (o *IdentityAccessManagementUpdateCredentialInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialInternalServerError  %+v", 500, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialInternalServerError) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialInternalServerError  %+v", 500, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialInternalServerError) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialGatewayTimeout creates a IdentityAccessManagementUpdateCredentialGatewayTimeout with default headers values
func NewIdentityAccessManagementUpdateCredentialGatewayTimeout() *IdentityAccessManagementUpdateCredentialGatewayTimeout {
	return &IdentityAccessManagementUpdateCredentialGatewayTimeout{}
}

/*
IdentityAccessManagementUpdateCredentialGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type IdentityAccessManagementUpdateCredentialGatewayTimeout struct {
	Payload *models.ZsrvResponse
}

// IsSuccess returns true when this identity access management update credential gateway timeout response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this identity access management update credential gateway timeout response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this identity access management update credential gateway timeout response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this identity access management update credential gateway timeout response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this identity access management update credential gateway timeout response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the identity access management update credential gateway timeout response
func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) Code() int {
	return 504
}

func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialGatewayTimeout  %+v", 504, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] identityAccessManagementUpdateCredentialGatewayTimeout  %+v", 504, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) GetPayload() *models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementUpdateCredentialDefault creates a IdentityAccessManagementUpdateCredentialDefault with default headers values
func NewIdentityAccessManagementUpdateCredentialDefault(code int) *IdentityAccessManagementUpdateCredentialDefault {
	return &IdentityAccessManagementUpdateCredentialDefault{
		_statusCode: code,
	}
}

/*
IdentityAccessManagementUpdateCredentialDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type IdentityAccessManagementUpdateCredentialDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this identity access management update credential default response has a 2xx status code
func (o *IdentityAccessManagementUpdateCredentialDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this identity access management update credential default response has a 3xx status code
func (o *IdentityAccessManagementUpdateCredentialDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this identity access management update credential default response has a 4xx status code
func (o *IdentityAccessManagementUpdateCredentialDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this identity access management update credential default response has a 5xx status code
func (o *IdentityAccessManagementUpdateCredentialDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this identity access management update credential default response a status code equal to that given
func (o *IdentityAccessManagementUpdateCredentialDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the identity access management update credential default response
func (o *IdentityAccessManagementUpdateCredentialDefault) Code() int {
	return o._statusCode
}

func (o *IdentityAccessManagementUpdateCredentialDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] IdentityAccessManagement_UpdateCredential default  %+v", o._statusCode, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialDefault) String() string {
	return fmt.Sprintf("[PUT /v1/credentials][%d] IdentityAccessManagement_UpdateCredential default  %+v", o._statusCode, o.Payload)
}

func (o *IdentityAccessManagementUpdateCredentialDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *IdentityAccessManagementUpdateCredentialDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
