// Code generated by go-swagger; DO NOT EDIT.

package resource_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResourceGroupEventsParams creates a new GetResourceGroupEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResourceGroupEventsParams() *GetResourceGroupEventsParams {
	return &GetResourceGroupEventsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourceGroupEventsParamsWithTimeout creates a new GetResourceGroupEventsParams object
// with the ability to set a timeout on a request.
func NewGetResourceGroupEventsParamsWithTimeout(timeout time.Duration) *GetResourceGroupEventsParams {
	return &GetResourceGroupEventsParams{
		timeout: timeout,
	}
}

// NewGetResourceGroupEventsParamsWithContext creates a new GetResourceGroupEventsParams object
// with the ability to set a context for a request.
func NewGetResourceGroupEventsParamsWithContext(ctx context.Context) *GetResourceGroupEventsParams {
	return &GetResourceGroupEventsParams{
		Context: ctx,
	}
}

// NewGetResourceGroupEventsParamsWithHTTPClient creates a new GetResourceGroupEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResourceGroupEventsParamsWithHTTPClient(client *http.Client) *GetResourceGroupEventsParams {
	return &GetResourceGroupEventsParams{
		HTTPClient: client,
	}
}

/*
GetResourceGroupEventsParams contains all the parameters to send to the API endpoint

	for the get resource group events operation.

	Typically these are written to a http.Request.
*/
type GetResourceGroupEventsParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	/* EnterpriseID.

	   system generated unique id for an enterprise (deprecated)
	*/
	EnterpriseID *string

	/* Objid.

	   Object id
	*/
	Objid string

	/* Objname.

	   Object name
	*/
	Objname *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resource group events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceGroupEventsParams) WithDefaults() *GetResourceGroupEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resource group events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceGroupEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resource group events params
func (o *GetResourceGroupEventsParams) WithTimeout(timeout time.Duration) *GetResourceGroupEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource group events params
func (o *GetResourceGroupEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource group events params
func (o *GetResourceGroupEventsParams) WithContext(ctx context.Context) *GetResourceGroupEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource group events params
func (o *GetResourceGroupEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource group events params
func (o *GetResourceGroupEventsParams) WithHTTPClient(client *http.Client) *GetResourceGroupEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource group events params
func (o *GetResourceGroupEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get resource group events params
func (o *GetResourceGroupEventsParams) WithXRequestID(xRequestID *string) *GetResourceGroupEventsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get resource group events params
func (o *GetResourceGroupEventsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithEnterpriseID adds the enterpriseID to the get resource group events params
func (o *GetResourceGroupEventsParams) WithEnterpriseID(enterpriseID *string) *GetResourceGroupEventsParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the get resource group events params
func (o *GetResourceGroupEventsParams) SetEnterpriseID(enterpriseID *string) {
	o.EnterpriseID = enterpriseID
}

// WithObjid adds the objid to the get resource group events params
func (o *GetResourceGroupEventsParams) WithObjid(objid string) *GetResourceGroupEventsParams {
	o.SetObjid(objid)
	return o
}

// SetObjid adds the objid to the get resource group events params
func (o *GetResourceGroupEventsParams) SetObjid(objid string) {
	o.Objid = objid
}

// WithObjname adds the objname to the get resource group events params
func (o *GetResourceGroupEventsParams) WithObjname(objname *string) *GetResourceGroupEventsParams {
	o.SetObjname(objname)
	return o
}

// SetObjname adds the objname to the get resource group events params
func (o *GetResourceGroupEventsParams) SetObjname(objname *string) {
	o.Objname = objname
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourceGroupEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.EnterpriseID != nil {

		// query param enterpriseId
		var qrEnterpriseID string

		if o.EnterpriseID != nil {
			qrEnterpriseID = *o.EnterpriseID
		}
		qEnterpriseID := qrEnterpriseID
		if qEnterpriseID != "" {

			if err := r.SetQueryParam("enterpriseId", qEnterpriseID); err != nil {
				return err
			}
		}
	}

	// path param objid
	if err := r.SetPathParam("objid", o.Objid); err != nil {
		return err
	}

	if o.Objname != nil {

		// query param objname
		var qrObjname string

		if o.Objname != nil {
			qrObjname = *o.Objname
		}
		qObjname := qrObjname
		if qObjname != "" {

			if err := r.SetQueryParam("objname", qObjname); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
