// Code generated by go-swagger; DO NOT EDIT.

package resource_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResourceGroupGetResourceGroupResourceMetricsByNameParams creates a new ResourceGroupGetResourceGroupResourceMetricsByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResourceGroupGetResourceGroupResourceMetricsByNameParams() *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	return &ResourceGroupGetResourceGroupResourceMetricsByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithTimeout creates a new ResourceGroupGetResourceGroupResourceMetricsByNameParams object
// with the ability to set a timeout on a request.
func NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithTimeout(timeout time.Duration) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	return &ResourceGroupGetResourceGroupResourceMetricsByNameParams{
		timeout: timeout,
	}
}

// NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithContext creates a new ResourceGroupGetResourceGroupResourceMetricsByNameParams object
// with the ability to set a context for a request.
func NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithContext(ctx context.Context) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	return &ResourceGroupGetResourceGroupResourceMetricsByNameParams{
		Context: ctx,
	}
}

// NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithHTTPClient creates a new ResourceGroupGetResourceGroupResourceMetricsByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewResourceGroupGetResourceGroupResourceMetricsByNameParamsWithHTTPClient(client *http.Client) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	return &ResourceGroupGetResourceGroupResourceMetricsByNameParams{
		HTTPClient: client,
	}
}

/*
ResourceGroupGetResourceGroupResourceMetricsByNameParams contains all the parameters to send to the API endpoint

	for the resource group get resource group resource metrics by name operation.

	Typically these are written to a http.Request.
*/
type ResourceGroupGetResourceGroupResourceMetricsByNameParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// EndTime.
	//
	// Format: date-time
	EndTime *strfmt.DateTime

	// EnterpriseID.
	EnterpriseID *string

	// Interval.
	//
	// Format: date-time
	Interval *strfmt.DateTime

	// MType.
	MType string

	// Objid.
	Objid *string

	// Objname.
	Objname string

	// Objtype.
	//
	// Default: "OBJECT_TYPE_UNSPECIFIED"
	Objtype *string

	// StartTime.
	//
	// Format: date-time
	StartTime *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resource group get resource group resource metrics by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithDefaults() *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resource group get resource group resource metrics by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetDefaults() {
	var (
		objtypeDefault = string("OBJECT_TYPE_UNSPECIFIED")
	)

	val := ResourceGroupGetResourceGroupResourceMetricsByNameParams{
		Objtype: &objtypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithTimeout(timeout time.Duration) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithContext(ctx context.Context) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithHTTPClient(client *http.Client) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithXRequestID(xRequestID *string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithEndTime adds the endTime to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithEndTime(endTime *strfmt.DateTime) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetEndTime(endTime *strfmt.DateTime) {
	o.EndTime = endTime
}

// WithEnterpriseID adds the enterpriseID to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithEnterpriseID(enterpriseID *string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetEnterpriseID(enterpriseID *string) {
	o.EnterpriseID = enterpriseID
}

// WithInterval adds the interval to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithInterval(interval *strfmt.DateTime) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetInterval(interval)
	return o
}

// SetInterval adds the interval to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetInterval(interval *strfmt.DateTime) {
	o.Interval = interval
}

// WithMType adds the mType to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithMType(mType string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetMType(mType)
	return o
}

// SetMType adds the mType to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetMType(mType string) {
	o.MType = mType
}

// WithObjid adds the objid to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithObjid(objid *string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetObjid(objid)
	return o
}

// SetObjid adds the objid to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetObjid(objid *string) {
	o.Objid = objid
}

// WithObjname adds the objname to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithObjname(objname string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetObjname(objname)
	return o
}

// SetObjname adds the objname to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetObjname(objname string) {
	o.Objname = objname
}

// WithObjtype adds the objtype to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithObjtype(objtype *string) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetObjtype(objtype)
	return o
}

// SetObjtype adds the objtype to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetObjtype(objtype *string) {
	o.Objtype = objtype
}

// WithStartTime adds the startTime to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WithStartTime(startTime *strfmt.DateTime) *ResourceGroupGetResourceGroupResourceMetricsByNameParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the resource group get resource group resource metrics by name params
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) SetStartTime(startTime *strfmt.DateTime) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *ResourceGroupGetResourceGroupResourceMetricsByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime strfmt.DateTime

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := qrEndTime.String()
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.EnterpriseID != nil {

		// query param enterpriseId
		var qrEnterpriseID string

		if o.EnterpriseID != nil {
			qrEnterpriseID = *o.EnterpriseID
		}
		qEnterpriseID := qrEnterpriseID
		if qEnterpriseID != "" {

			if err := r.SetQueryParam("enterpriseId", qEnterpriseID); err != nil {
				return err
			}
		}
	}

	if o.Interval != nil {

		// query param interval
		var qrInterval strfmt.DateTime

		if o.Interval != nil {
			qrInterval = *o.Interval
		}
		qInterval := qrInterval.String()
		if qInterval != "" {

			if err := r.SetQueryParam("interval", qInterval); err != nil {
				return err
			}
		}
	}

	// path param mType
	if err := r.SetPathParam("mType", o.MType); err != nil {
		return err
	}

	if o.Objid != nil {

		// query param objid
		var qrObjid string

		if o.Objid != nil {
			qrObjid = *o.Objid
		}
		qObjid := qrObjid
		if qObjid != "" {

			if err := r.SetQueryParam("objid", qObjid); err != nil {
				return err
			}
		}
	}

	// path param objname
	if err := r.SetPathParam("objname", o.Objname); err != nil {
		return err
	}

	if o.Objtype != nil {

		// query param objtype
		var qrObjtype string

		if o.Objtype != nil {
			qrObjtype = *o.Objtype
		}
		qObjtype := qrObjtype
		if qObjtype != "" {

			if err := r.SetQueryParam("objtype", qObjtype); err != nil {
				return err
			}
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime strfmt.DateTime

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := qrStartTime.String()
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
