// Code generated by go-swagger; DO NOT EDIT.

package patch_envelope

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchEnvelopeConfigurationDeletePatchEnvelopeParams creates a new PatchEnvelopeConfigurationDeletePatchEnvelopeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchEnvelopeConfigurationDeletePatchEnvelopeParams() *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	return &PatchEnvelopeConfigurationDeletePatchEnvelopeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithTimeout creates a new PatchEnvelopeConfigurationDeletePatchEnvelopeParams object
// with the ability to set a timeout on a request.
func NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithTimeout(timeout time.Duration) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	return &PatchEnvelopeConfigurationDeletePatchEnvelopeParams{
		timeout: timeout,
	}
}

// NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithContext creates a new PatchEnvelopeConfigurationDeletePatchEnvelopeParams object
// with the ability to set a context for a request.
func NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithContext(ctx context.Context) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	return &PatchEnvelopeConfigurationDeletePatchEnvelopeParams{
		Context: ctx,
	}
}

// NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithHTTPClient creates a new PatchEnvelopeConfigurationDeletePatchEnvelopeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchEnvelopeConfigurationDeletePatchEnvelopeParamsWithHTTPClient(client *http.Client) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	return &PatchEnvelopeConfigurationDeletePatchEnvelopeParams{
		HTTPClient: client,
	}
}

/*
PatchEnvelopeConfigurationDeletePatchEnvelopeParams contains all the parameters to send to the API endpoint

	for the patch envelope configuration delete patch envelope operation.

	Typically these are written to a http.Request.
*/
type PatchEnvelopeConfigurationDeletePatchEnvelopeParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	/* ID.

	   System defined universally unique Id of the patch envelope
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch envelope configuration delete patch envelope params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithDefaults() *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch envelope configuration delete patch envelope params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithTimeout(timeout time.Duration) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithContext(ctx context.Context) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithHTTPClient(client *http.Client) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithXRequestID(xRequestID *string) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithID adds the id to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WithID(id string) *PatchEnvelopeConfigurationDeletePatchEnvelopeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch envelope configuration delete patch envelope params
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchEnvelopeConfigurationDeletePatchEnvelopeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
