// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Deployment deployment
//
// swagger:model Deployment
type Deployment struct {

	// list of app instance policies
	AppInstPolicies []*AppInstPolicy `json:"appInstPolicies"`

	// cluster policy details
	ClusterPolicy *ClusterInstPolicy `json:"clusterPolicy,omitempty"`

	// user defined tag for the deployment, which is used while targeting set of devices
	DeploymentTag string `json:"deploymentTag,omitempty"`

	// list of device policies
	DevicePolicies []*DevicePolicy `json:"devicePolicies"`

	// system generated unique id for an deployment
	ID string `json:"id,omitempty"`

	// integration policy details
	IntegrationPolicy *IntegrationPolicy `json:"integrationPolicy,omitempty"`

	// user defined name for the deployment
	Name string `json:"name,omitempty"`

	// list of network instance policies
	NetworkInstPolicies []*NetworkInstPolicy `json:"networkInstPolicies"`

	// object revision
	Revision *ObjectRevision `json:"revision,omitempty"`

	// user defined title for the deployment
	Title string `json:"title,omitempty"`

	// list of volume instamce policies
	VolumeInstPolicies []*VolumeInstPolicy `json:"volumeInstPolicies"`
}

// Validate validates this deployment
func (m *Deployment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppInstPolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDevicePolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIntegrationPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkInstPolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRevision(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVolumeInstPolicies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Deployment) validateAppInstPolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.AppInstPolicies) { // not required
		return nil
	}

	for i := 0; i < len(m.AppInstPolicies); i++ {
		if swag.IsZero(m.AppInstPolicies[i]) { // not required
			continue
		}

		if m.AppInstPolicies[i] != nil {
			if err := m.AppInstPolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("appInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("appInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) validateClusterPolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.ClusterPolicy) { // not required
		return nil
	}

	if m.ClusterPolicy != nil {
		if err := m.ClusterPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clusterPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("clusterPolicy")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) validateDevicePolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.DevicePolicies) { // not required
		return nil
	}

	for i := 0; i < len(m.DevicePolicies); i++ {
		if swag.IsZero(m.DevicePolicies[i]) { // not required
			continue
		}

		if m.DevicePolicies[i] != nil {
			if err := m.DevicePolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("devicePolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("devicePolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) validateIntegrationPolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.IntegrationPolicy) { // not required
		return nil
	}

	if m.IntegrationPolicy != nil {
		if err := m.IntegrationPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("integrationPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("integrationPolicy")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) validateNetworkInstPolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkInstPolicies) { // not required
		return nil
	}

	for i := 0; i < len(m.NetworkInstPolicies); i++ {
		if swag.IsZero(m.NetworkInstPolicies[i]) { // not required
			continue
		}

		if m.NetworkInstPolicies[i] != nil {
			if err := m.NetworkInstPolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) validateRevision(formats strfmt.Registry) error {
	if swag.IsZero(m.Revision) { // not required
		return nil
	}

	if m.Revision != nil {
		if err := m.Revision.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("revision")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("revision")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) validateVolumeInstPolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.VolumeInstPolicies) { // not required
		return nil
	}

	for i := 0; i < len(m.VolumeInstPolicies); i++ {
		if swag.IsZero(m.VolumeInstPolicies[i]) { // not required
			continue
		}

		if m.VolumeInstPolicies[i] != nil {
			if err := m.VolumeInstPolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("volumeInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("volumeInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this deployment based on the context it is used
func (m *Deployment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAppInstPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClusterPolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDevicePolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIntegrationPolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworkInstPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRevision(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVolumeInstPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Deployment) contextValidateAppInstPolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AppInstPolicies); i++ {

		if m.AppInstPolicies[i] != nil {
			if err := m.AppInstPolicies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("appInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("appInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) contextValidateClusterPolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.ClusterPolicy != nil {
		if err := m.ClusterPolicy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clusterPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("clusterPolicy")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) contextValidateDevicePolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DevicePolicies); i++ {

		if m.DevicePolicies[i] != nil {
			if err := m.DevicePolicies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("devicePolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("devicePolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) contextValidateIntegrationPolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.IntegrationPolicy != nil {
		if err := m.IntegrationPolicy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("integrationPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("integrationPolicy")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) contextValidateNetworkInstPolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NetworkInstPolicies); i++ {

		if m.NetworkInstPolicies[i] != nil {
			if err := m.NetworkInstPolicies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Deployment) contextValidateRevision(ctx context.Context, formats strfmt.Registry) error {

	if m.Revision != nil {
		if err := m.Revision.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("revision")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("revision")
			}
			return err
		}
	}

	return nil
}

func (m *Deployment) contextValidateVolumeInstPolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VolumeInstPolicies); i++ {

		if m.VolumeInstPolicies[i] != nil {
			if err := m.VolumeInstPolicies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("volumeInstPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("volumeInstPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Deployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Deployment) UnmarshalBinary(b []byte) error {
	var res Deployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
